### ISSUE TITLE
Handle meetup card & page layout for 'more info coming soon' event

### ISSUE THREAD

**Issue by jmsv** [fusion-meetup/fusion-meetup-web#55]
For implementation I'm thinking:

- Add a bool to the event schema for `moreInfoComingSoon` or similar
- If true, display a lil banner like "more info coming soon!"
- and don't render sections for speakers etc.

**Comment by jmsv** [comment]
@ukmadlz you on this one or shall I grab it?

**Comment by ukmadlz** [comment]
I don't think another object on the event schema makes sense. We can either infer from the number of speakers (2 or fewer means more) or it doesn't really matter.

**Comment by ukmadlz** [comment]
Yeah. I'd agree

**Comment by jmsv** [comment]
> Yeah. I'd agree

cool! you wanna sort this?

**Comment by ukmadlz** [comment]
Nearly done
